shard.yml
src/sam.cr
src/tasks/entities.cr

feat(entitites:application): support specifying `redirect_uri`

---

shard.lock
shard.yml
src/tasks/entities.cr
src/tasks/initialization.cr

Creates a `Repository` entitity for `backoffice`
Component of PlaceOS/frontends/issues/2

feat(start): create backoffice interface repository

---

Dockerfile
shard.lock
shard.yml
src/log.cr

Note: the logging output seems incorrect.
The log backend is setup like so..
https://github.com/PlaceOS/init/blob/d54553a3007388da3be4ccee97a3146d84426cb3/src/log.cr#L1-L6
Yet still produces the following output
```
...
2020-06-17T05:37:49.348481Z   INFO - tasks.entities: using existing ControlSystem<sys-F97rxMebpD9>
level=INFO time=2020-06-17T05:37:49Z source=tasks.entities message=using existing ControlSystem<sys-F97rxMebpD9>
2020-06-17T05:37:49.349811Z   INFO - tasks.entities: using existing Settings<sets-F9A0-Ko-kir>
level=INFO time=2020-06-17T05:37:49Z source=tasks.entities message=using existing Settings<sets-F9A0-Ko-kir>
2020-06-17T05:37:49.351545Z   INFO - tasks.entities: using existing Module<mod-F982Tf7jRm2>
level=INFO time=2020-06-17T05:37:49Z source=tasks.entities …
```

build: support 0.35.0

---

src/tasks/entities.cr
src/utils/s3.cr

Created `upsert_document` document to DRY out some of the repeititve upsert logic.

refactor(entities): dry out document creation methods

---

Dockerfile
scripts/generate-secrets

component of place-labs/partner-environment/pull/14

feat: add secrets generation script

---

shard.lock
shard.yml
src/tasks/entities.cr

Include `PlaceOS::Model::Edge` placeholder to initialisation

feat(entities): add edge model to placeholder documents

---

shard.lock
shard.yml
src/constants.cr
src/restore.cr
src/tasks/entities.cr
src/tasks/restore.cr
src/utils/rethinkdb.cr
src/utils/s3.cr

fix(task:restore): remove KMS

---

Dockerfile

Drop the `scripts` dir into the container and add them to the path

build(Dockerfile): add scripts to path

---

Dockerfile
shard.lock
shard.override.yml

- Adds support for crystal 0.36.1
- Adds binaries and scripts to the path

feat: 0.36.1

---

shard.lock
shard.yml
src/log.cr
src/tasks/backup.cr
src/tasks/database.cr
src/tasks/entities.cr
src/tasks/initialization.cr

Adds [placeos/log-backend](https://github.com/place-labs/log-backend).

feat(logstash): add placeos-log-backend

---

Dockerfile
scripts/generate-secrets

During generate-secrets, create htpasswd file for nginx basic auth of kibana route
Uses `PLACE_EMAIL` and `PLACE_PASSWORD`

feat(secrets): generate kibana htpasswd

---

shard.lock
shard.yml
src/tasks/entities.cr

- Adds placeholder `Model::Zone` for each hierarchical zone tag. i.e. `building`, `org`, `level`, `area`
- Removes `Test` prefix from development entities

feat(entities): add hierarchy zones

---

shard.lock
shard.yml
src/constants.cr
src/log.cr
src/logging.cr
src/migration.cr
src/tasks/backup.cr
src/tasks/database.cr
src/tasks/entities.cr
src/tasks/initialization.cr

configure `Log.progname` for the purpose of rendering in logstash

feat(logging): configure `Log.progname`

---

src/tasks/initialization.cr

Simple change from where that changes the default branch
- *development*: `build-alpha` -> `build/dev`
- *production*: `build-release` -> `build/prod`

refactor(initialization): change default backoffice branch to build/(dev|prod)

---

Dockerfile
README.md
scripts/generate-secrets
src/sam.cr
src/tasks/entities.cr

Task to check for user presence given domain and email.
Useful for setup automation.

feat(tasks): add a check for user existence

---

Dockerfile

Support `CRYSTAL_VERSION` build argument when building the image

build(Dockerfile): normalize CRYSTAL_VERSION arg

---

README.md
shard.yml
src/constants.cr
src/start.cr
src/tasks/backup.cr
src/tasks/entities.cr
src/tasks/initialization.cr

Adds two new environment variables...
- `PLACE_BACKOFFCE_COMMIT`
- `PLACE_BACKOFFCE_BRANCH`
This enables specifying a pin for backoffice.
Related to https://github.com/place-labs/partner-environment/issues/77

feat(initialization): support pinning interface

---

shard.lock
src/tasks/entities.cr

Supports changes in placeos/models#123

refactor(user): use new Email struct

---

scripts/generate-secrets

fix: allow spaces in password

---

shard.lock
src/sam.cr

**Description of the change**
Bump to latest models

build(shard.lock): bump shards

---

src/migrations/1.2203-000-metadata_details_json.cr
src/migrations/1.2204-000-metadata_details_json.cr

**Description of the change**
Converts `Metdata.details` string column into a JSON backed column
**Applicable issues**
- Closes #56

refactor(metadata): migrate Metadata.details to JSON

---

Dockerfile
shard.lock
shard.override.yml
shard.yml
src/tasks/secrets.cr

use a pure crystal implementation
possible fix for https://github.com/PlaceOS/local/issues/132

feat: remove libsodium requirement

---

src/migrations/1.2210-000-cleanup_doorkeeper_grants.cr

Delete doorkeper grants without a ttl to free up space.

fix(grant): remove doorkeeper grants without a ttl

---

shard.lock
src/tasks/entities.cr

fix(entities): adds building, level parent property. Fixes #82

---

Dockerfile

Add Timezone data to final image.

fix(dockerfile): Add tzdata for timezone in final image

---

db/migrations/20221103144813_add_doorkeeper_table.sql
db/migrations/20221103144834_add_condo_table.sql
db/migrations/20230224115858_add_sys_booking_feat.sql
db/migrations/20230406153149_add_tenant_table.sql
db/migrations/20230406225814_add_event_metadata_table.sql
db/migrations/20230416212548_add_guest_table.sql
db/migrations/20230416213508_add_attendee_table.sql
db/migrations/20230416215414_add_booking_table.sql
db/migrations/20230416220259_add_survey_table.sql

* Added checks in existing schema to avoid DDL generation conflicts
* Added migration schema for `staff-api` models.
Related: https://github.com/PlaceOS/models/pull/201

migration: added schema generation for staf-api models
